### ISSUE TITLE
Longest Common Subsequence in Java

### ISSUE THREAD

**Issue by sumana2001** [Aniket762/Project-alpha#64]

**Comment by AnkitaM84** [comment]
Hey I would like to take this up!

**Comment by sumana2001** [comment]
@AnkitaM84 Sure! Go ahead😀

**Comment by AnkitaM84** [comment]
Since this is my first ever pull request, I am not sure how to do it. It would be great if you can just tell me that while creating a pull request, do i have to choose "commit to the main branch" or "create a new branch for this commit and start a pull request"
I mean..this is kind of embarassing to ask but I thought better to ask that to do something wrong

**Comment by AnkitaM84** [comment]
I have created a pull request #97 . Do take a look at it. Thanks :)
